mandofashion/Areas/PrivatePages/Controllers/NewArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mandofashion.Models;
using System.IO;

namespace DoAnLTW.Areas.PrivatePages.Controllers
{
    public class NewArticlesController : Controller
    {
        // GET: PrivatePages/NewArticles
        [HttpGet]
        public ActionResult Index()
        {
            BaiViet x = new BaiViet();
            //--thiết lập thông tin cho bài viết 1 cách tự động [Khách quan]
            x.ngayDang = DateTime.Now;
            x.soLanDoc = 0;
            TaiKhoan tk = Session["TtDangNhap"] as TaiKhoan;
            x.taiKhoan = ThuongDung.GetTenTaiKhoan();
            //--Để đưa đường dẫn hình ra ngoài hiển thị trên image
            ViewBag.ddHinh = "~/Images/_0000_h732_2_.jpg";
            return View(x);
        }
        [HttpPost]
        public ActionResult Index(BaiViet x, HttpPostedFileBase HinhDaiDien)
        {
            //--B1: Xử lí thông tin đã nhận từ view
            x.maBV = string.Format("{0:yyMMddhhmm}", DateTime.Now);
            x.daDuyet = false;
            x.ngayDang = DateTime.Now;
            x.taiKhoan = ThuongDung.GetTenTaiKhoan();
            x.soLanDoc = 0;
            x.loaiTin = "QC";
            if (HinhDaiDien != null)
            {
                //Lưu hình vào thư mục chứ bài viết 
                string virPath = "Images/";
                string phyPath = Server.MapPath("~/" + virPath); // Xác định vị trí lưu hình sao khi upload
                string ext = Path.GetExtension(HinhDaiDien.FileName);
                string tenF = "HinhDD" + x.maBV + "." + ext;
                HinhDaiDien.SaveAs(phyPath + tenF); //lưu thì phải dựa vào đường vật lí
                //ghi nhận đường dẫn truy cập tới hình đã lưu trữ dựa vào domain
                x.hinhDD = virPath + tenF;  //đường đẫn ảo theo domain 
                                            //x.hinhDD
                ViewBag.ddHinh = x.hinhDD;
                //sẽ cập nhật hình vừa chọn cho giao diện              
            }
            else
            {
                x.hinhDD = "";
            }
            //--B2: Cập nhật đối tượng bài viết vừa đăng vào model
            ShopOnline_DemoEntities1 db = new ShopOnline_DemoEntities1();
            db.BaiViets.Add(x);
            //--B3: Lưu thông tin xuống Database
            db.SaveChanges();
            return View(x);
        }
    }
}

mandofashion/Areas/PrivatePages/Views/NewArticles/Index.cshtml
@model mandofashion.BaiViet
@{
    ViewBag.Title = "Index";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>General Form</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">General Form</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            @using (Html.BeginForm("Index", "NewArticles", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-8">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Thông tin chính</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Tên bài viết</label>
                                    @Html.TextBoxFor(m => m.tenBV, new { @class = "form-control", @placeholder = "Nhập tên bài viết" })
                                </div>
                                <div class="form-group">
                                    <label for="ndtt">Nội dung tóm tắt</label>
                                    @Html.TextAreaFor(m => m.ndTomTat, new { @class = "form-control", @rows = "5", @placeholder = "Nhập nội dung tóm tắt bài viết", @id = "vungSoanThao" })
                                </div>
                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label for="ndtt">Ngày đăng</label>
                                            @Html.TextBoxFor(m => m.ngayDang, new { @class = "form-control", @disabled = "disabled" })
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label for="ndtt">Tài khoản</label>
                                            @Html.TextBoxFor(m => m.taiKhoan, new { @class = "form-control", @disabled = "disabled" })
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label for="ndtt">Số lần đọc</label>
                                            @Html.TextBoxFor(m => m.soLanDoc, new { @class = "form-control", @disabled = "disabled" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <!-- general form elements disabled -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Thêm hình ảnh</h3>
                            </div>
                            <div class="form-group">
                                <img src="@ViewBag.ddHinh" class="img-thumbnail" style="width:100%;" />
                                <label for="exampleInputFile">Hình ảnh</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="exampleInputFile" name="HinhD">
                                        <label class="custom-file-label" for="exampleInputFile">Chọn file</label>
                                    </div>
                                    <div class="input-group-append">
                                        <span class="input-group-text">Tải lên</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/.col (left) -->
                    <!-- /.card-body -->
                    <!-- right column -->
                    <div class="col-md-12">
                        <div class="card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Nội dung bài viết</h3>
                            </div>
                            <div class="card-body">
                                <div class="mb-3">
                                    @Html.TextAreaFor(m => m.noiDung, new
                                    {
                                   @id = "vungSoanThao",
                                        @class = "textarea",
                                        @placeholder = "Nhập nội dung bài viết",
                                   @style = "width: 100%; height: 600px;" +
                                   "font-size: 14; line-height: 18px; border: 1px solid; #dddd;padding:10px;"
                                    })
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/.col (right) -->
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary">Xác nhận</button>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.row -->
            }
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
<!--scripts-->
<script src="https://cdn.tiny.cloud/1/3otmxje9q4ejjzffnafnhmseqgntu0fzphpomkopvdljogva/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: 'textarea#vungSoanThao',
        plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
        mergetags_list: [
            { value: 'First.Name', title: 'First Name' },
            { value: 'Email', title: 'Email' },
        ]
    });
</script>
<!--/.scripts-->